export const OUTFIT_TOGGLE_SAVE = 'OUTFIT_TOGGLE_SAVE'
export const OUTFIT_ADD_TO_SCHEDULE = 'OUTFIT_ADD_TO_SCHEDULE'
export const OUTFIT_SHOW_ALTERNATIVES = 'OUTFIT_SHOW_ALTERNATIVES'
export const NAVIGATE_TO_OUTFIT_DETAIL = 'NAVIGATE_TO_OUTFIT_DETAIL'

